JobTracking.UI/Areas/Admin/Controllers/AciliyetController.cs
using JobTracking.Business.Interfaces;
using JobTracking.Entity.Concrete;
using JobTracking.UI.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobTracking.UI.Areas.Admin
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class AciliyetController : Controller
    {
        private readonly IAciliyetService _aciliyetService;
        public AciliyetController(IAciliyetService aciliyetService)
        {
            _aciliyetService = aciliyetService;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "aciliyet";
            List<Aciliyet> aciliyetler= _aciliyetService.Getirhepsi();

            List<AciliyetListViewModel> model = new List<AciliyetListViewModel>();
            foreach (var item in aciliyetler)
            {
                AciliyetListViewModel aciliyetModel = new AciliyetListViewModel();
                aciliyetModel.Id = item.Id;
                aciliyetModel.Tanim = item.Tanim;
                model.Add(aciliyetModel);
            }
            return View(model);
        }
        public IActionResult EkleAciliyet()
        {
            TempData["Active"] = "aciliyet";
            return View(new AciliyetAddViewModel());
        }
        [HttpPost]
        public IActionResult EkleAciliyet(AciliyetAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                _aciliyetService.Kaydet(new Aciliyet() {
                Tanim=model.Tanim
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult GuncelleAciliyet(int id)
        {
            TempData["Active"] = "aciliyet";
            var aciliyet= _aciliyetService.GetirIdile(id);
            AciliyetUpdateViewModel model = new AciliyetUpdateViewModel
            {
                Id = aciliyet.Id,
                Tanim = aciliyet.Tanim
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult GuncelleAciliyet(AciliyetUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _aciliyetService.Guncelle(new Aciliyet
                {
                    Tanim = model.Tanim,
                    Id = model.Id
                });
                return RedirectToAction("Index");
            }
            return View(model);

        }
    }
}

JobTracking.UI/Areas/Admin/Views/Aciliyet/EkleAciliyet.cshtml
@model AciliyetAddViewModel
@{
    ViewData["Title"] = "EkleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3" method="post">
    <div class="form-group">
        <label asp-for="Tanim"></label>
        <span asp-validation-for="Tanim"></span>
        <input asp-for="Tanim" type="text" class="form-control" />
    </div>
    <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-check mr-2"></i> Kaydet</button>
</form>

@section JavaScript{

    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>

}

JobTracking.UI/Areas/Admin/Views/Aciliyet/GuncelleAciliyet.cshtml
@model AciliyetUpdateViewModel
@{
    ViewData["Title"] = "GuncelleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-action="GuncelleAciliyet" class="w-75 mx-auto p-3" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Tanim"></label>
        <span asp-validation-for="Tanim"></span>
        <input asp-for="Tanim" type="text" class="form-control" />
    </div>
    <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-check mr-2"></i> Kaydet</button>
</form>

@section JavaScript{

    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>

}

JobTracking.UI/Areas/Admin/Views/Aciliyet/Index.cshtml
@model List<AciliyetListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
 

@if (Model.Count != 0)
{
    <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-outline-dark my-2"><i class="fas fa-plus-circle mr-2"></i> Yeni Aciliyet</a>
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Tanım</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Tanim</td>
                    <td>
                        <a asp-action="GuncelleAciliyet" asp-controller="Aciliyet" asp-route-id="@item.Id" class="btn btn-warning btn-sm"><i class="fa fa-edit mr-2"></i> Düzenle</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <div class="text-center lead mt-4">
        <p class="lead">
            Sistemde kayıtlı aciliyet durumu bulunamadı
        </p>
        <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-info my-2">Yeni Aciliyet Ekle</a>
    </div>
}